apiVersion: v1
kind: Service
metadata:
  namespace: homework
  name: websrv-service
spec:
  type: ClusterIP
  selector:
    app: homework-websrv
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: websrv-port
